[tasks.dev]
script = "cargo watch -x clippy -x fmt -x run"

[tasks.image]
script = "cpln image build --name ${CARGO_MAKE_CRATE_NAME}:${CARGO_MAKE_CRATE_VERSION} -- --builder paketobuildpacks/builder-jammy-buildpackless-full:latest --buildpack paketo-community/rust@0.32.0 --run-image paketobuildpacks/run-jammy-base:latest"

[tasks.up]
script = "docker run --name ${CARGO_MAKE_CRATE_NAME} -p 8080:8080 thekwoka.registry.cpln.io/${CARGO_MAKE_CRATE_NAME}:${CARGO_MAKE_CRATE_VERSION}"
dependencies = ["image"]

[tasks.down]
script = "docker rm -f ${CARGO_MAKE_CRATE_NAME}"

[tasks.start]
script = "docker start ${CARGO_MAKE_CRATE_NAME}"

[tasks.stop]
script = "docker stop ${CARGO_MAKE_CRATE_NAME}"

[tasks.push]
script = "cpln image build --name ${CARGO_MAKE_CRATE_NAME}:${CARGO_MAKE_CRATE_VERSION} --push -- --builder paketobuildpacks/builder-jammy-buildpackless-full:latest --buildpack paketo-community/rust@0.32.0 --run-image paketobuildpacks/run-jammy-base:latest"

[tasks.deploy]
script = "cpln image build --name ${CARGO_MAKE_CRATE_NAME}:latest --push -- --builder paketobuildpacks/builder-jammy-buildpackless-full:latest --buildpack paketo-community/rust@0.32.0 --run-image paketobuildpacks/run-jammy-base:latest"

[tasks.db-up]
script = "docker run --name surrealdb --rm --pull always -p 8000:8000 surrealdb/surrealdb:latest start"

[tasks.db-down]
script = "docker rm -f surrealdb"

[tasks.cpln-create]
script = "cpln workload create --name url-shortener-preview --image //image/url-shortener:0.0.1 --port 8080 --public --gvc url-shorten --org thekwoka --type standard --cpu 2m --mem 10Mi"
