name: Perform Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Lint-Test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        name: Setup Cargo cache
        with:
          cache-all-crates: true

      - name: Install nextest
        run: cargo install cargo-nextest cargo-sweep

      - name: Preclean cache
        run: cargo sweep -ir

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Test
        run: cargo nextest run

      - name: Clean Cache
        run: cargo sweep -rt 7
