name: Perform Tests

on:
  pull_request:
    branches:
      - main
jobs:
  Lint-Test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - run: |
          echo '[registries.crates-io]' >> ~/.cargo/config.toml
          echo 'protocol = "sparse"' >> ~/.cargo/config.toml

      - uses: Swatinem/rust-cache@v2
        name: Setup Cargo cache
        with:
          cache-all-crates: true

      - name: Install nextest
        run: cargo install cargo-nextest

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Test
        run: cargo nextest run
